gui:
  returnImmediately: true
  theme:
    activeBorderColor:
      - '#b4befe'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
