[display]
use_pager = true

[updates]
auto_update = true
auto_update_interval_hours = 168

# Catppuccin Mocha style
[style.command_name]
foreground = { rgb = { r = 137, g = 180, b = 250 } }   # Blue
bold = true

[style.example_text]
foreground = { rgb = { r = 166, g = 173, b = 200 } }   # Subtext0

[style.example_code]
foreground = { rgb = { r = 166, g = 227, b = 161 } }   # Green

[style.example_variable]
foreground = { rgb = { r = 250, g = 179, b = 135 } }   # Peach
underline = true
italic = true

[style.description]
foreground = { rgb = { r = 205, g = 214, b = 244 } }   # Text

[style.parameter_name]
foreground = { rgb = { r = 249, g = 226, b = 175 } }   # Yellow
bold = true

[style.parameter_variable]
foreground = { rgb = { r = 243, g = 139, b = 168 } }   # Red
italic = true

[style.option_name]
foreground = { rgb = { r = 180, g = 190, b = 254 } }   # Lavender

[style.option_alias]
foreground = { rgb = { r = 203, g = 166, b = 247 } }   # Mauve

[style.option_value]
foreground = { rgb = { r = 148, g = 226, b = 213 } }   # Teal

[style.literal]
foreground = { rgb = { r = 245, g = 194, b = 231 } }   # Pink
